/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/stakater/Forecastle/pkg/apis/forecastle/v1alpha1"
	scheme "github.com/stakater/Forecastle/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ForecastleAppsGetter has a method to return a ForecastleAppInterface.
// A group's client should implement this interface.
type ForecastleAppsGetter interface {
	ForecastleApps(namespace string) ForecastleAppInterface
}

// ForecastleAppInterface has methods to work with ForecastleApp resources.
type ForecastleAppInterface interface {
	Create(*v1alpha1.ForecastleApp) (*v1alpha1.ForecastleApp, error)
	Update(*v1alpha1.ForecastleApp) (*v1alpha1.ForecastleApp, error)
	UpdateStatus(*v1alpha1.ForecastleApp) (*v1alpha1.ForecastleApp, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ForecastleApp, error)
	List(opts v1.ListOptions) (*v1alpha1.ForecastleAppList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ForecastleApp, err error)
	ForecastleAppExpansion
}

// forecastleApps implements ForecastleAppInterface
type forecastleApps struct {
	client rest.Interface
	ns     string
}

// newForecastleApps returns a ForecastleApps
func newForecastleApps(c *ForecastleV1alpha1Client, namespace string) *forecastleApps {
	return &forecastleApps{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the forecastleApp, and returns the corresponding forecastleApp object, and an error if there is any.
func (c *forecastleApps) Get(name string, options v1.GetOptions) (result *v1alpha1.ForecastleApp, err error) {
	result = &v1alpha1.ForecastleApp{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("forecastleapps").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ForecastleApps that match those selectors.
func (c *forecastleApps) List(opts v1.ListOptions) (result *v1alpha1.ForecastleAppList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ForecastleAppList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("forecastleapps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested forecastleApps.
func (c *forecastleApps) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("forecastleapps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a forecastleApp and creates it.  Returns the server's representation of the forecastleApp, and an error, if there is any.
func (c *forecastleApps) Create(forecastleApp *v1alpha1.ForecastleApp) (result *v1alpha1.ForecastleApp, err error) {
	result = &v1alpha1.ForecastleApp{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("forecastleapps").
		Body(forecastleApp).
		Do().
		Into(result)
	return
}

// Update takes the representation of a forecastleApp and updates it. Returns the server's representation of the forecastleApp, and an error, if there is any.
func (c *forecastleApps) Update(forecastleApp *v1alpha1.ForecastleApp) (result *v1alpha1.ForecastleApp, err error) {
	result = &v1alpha1.ForecastleApp{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("forecastleapps").
		Name(forecastleApp.Name).
		Body(forecastleApp).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *forecastleApps) UpdateStatus(forecastleApp *v1alpha1.ForecastleApp) (result *v1alpha1.ForecastleApp, err error) {
	result = &v1alpha1.ForecastleApp{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("forecastleapps").
		Name(forecastleApp.Name).
		SubResource("status").
		Body(forecastleApp).
		Do().
		Into(result)
	return
}

// Delete takes name of the forecastleApp and deletes it. Returns an error if one occurs.
func (c *forecastleApps) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("forecastleapps").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *forecastleApps) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("forecastleapps").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched forecastleApp.
func (c *forecastleApps) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ForecastleApp, err error) {
	result = &v1alpha1.ForecastleApp{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("forecastleapps").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
