version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: 'npm'
  directory: '/frontend'
  schedule:
    interval: 'weekly'