/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	forecastlev1alpha1 "github.com/stakater/Forecastle/pkg/apis/forecastle/v1alpha1"
	versioned "github.com/stakater/Forecastle/pkg/client/clientset/versioned"
	internalinterfaces "github.com/stakater/Forecastle/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/stakater/Forecastle/pkg/client/listers/forecastle/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ForecastleAppInformer provides access to a shared informer and lister for
// ForecastleApps.
type ForecastleAppInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ForecastleAppLister
}

type forecastleAppInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewForecastleAppInformer constructs a new informer for ForecastleApp type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewForecastleAppInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredForecastleAppInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredForecastleAppInformer constructs a new informer for ForecastleApp type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredForecastleAppInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ForecastleV1alpha1().ForecastleApps(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ForecastleV1alpha1().ForecastleApps(namespace).Watch(options)
			},
		},
		&forecastlev1alpha1.ForecastleApp{},
		resyncPeriod,
		indexers,
	)
}

func (f *forecastleAppInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredForecastleAppInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *forecastleAppInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&forecastlev1alpha1.ForecastleApp{}, f.defaultInformer)
}

func (f *forecastleAppInformer) Lister() v1alpha1.ForecastleAppLister {
	return v1alpha1.NewForecastleAppLister(f.Informer().GetIndexer())
}
