{{- if .Values.forecastle.ingress.enabled -}}
{{- if and .Values.forecastle.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.forecastle.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.forecastle.ingress.annotations "kubernetes.io/ingress.class" .Values.forecastle.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "forecastle.name" . }}
  labels:
{{ include "forecastle.labels.stakater" . | indent 4 }}
{{ include "forecastle.labels.chart" . | indent 4 }}
  {{- with .Values.forecastle.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.forecastle.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.forecastle.ingress.className }}
  {{- end }}
{{- if .Values.forecastle.ingress.tls }}
  tls:
  {{- range .Values.forecastle.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.forecastle.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ template "forecastle.name" $ }}
                port:
                  name: http
              {{- else }}
              serviceName: {{ template "forecastle.name" $ }}
              servicePort: http
          {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
