apiVersion: v1
kind: Service
metadata:
{{- if .Values.forecastle.service.annotations }}
  annotations:
{{ toYaml .Values.forecastle.service.annotations | indent 4 }}
{{- end }}
  labels:
{{ include "forecastle.labels.stakater" . | indent 4 }}
{{ include "forecastle.labels.chart" . | indent 4 }}
    expose: "{{ .Values.forecastle.service.expose }}"
  name: {{ template "forecastle.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  ports:
  {{- if .Values.forecastle.openshiftOauthProxy.enabled }}
  - name: http
    port: 443
    protocol: TCP
    targetPort: 8443
  {{- else }}
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  {{- end }}
  selector:
{{ include "forecastle.labels.selector" . | indent 4 }}
