apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: forecastleapps.forecastle.stakater.com
spec:
  conversion:
    strategy: None
  group: forecastle.stakater.com
  names:
    kind: ForecastleApp
    listKind: ForecastleAppList
    plural: forecastleapps
    singular: forecastleapp
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              group:
                type: string
              icon:
                type: string
              instance:
                type: string
              name:
                type: string
              networkRestricted:
                type: boolean
              properties:
                additionalProperties:
                  type: string
                type: object
              url:
                type: string
              urlFrom:
                properties:
                  ingressRef:
                    type: object
                    properties:
                      name:
                        type: string
                  routeRef:
                    type: object
                    properties:
                      name:
                        type: string
                type: object
            required:
            - name
            - group
            - icon
            type: object
          status:
            type: object
    served: true
    storage: true
    subresources:
      status: {}
